  PDM-26[m
  all[m
  dev[m
  feature/PDM-17-melhorar-apresentacao-em-telas-grandes[m
  feature/PDM-19-testes[m
  feature/PDM-20-outros-testes[m
  feature/PDM-21-testelalal[m
  feature/PDM-22-criando-validacao-do-usuario-por-meio-do-jwt[m
  feature/PDM-27-ajuste-na-reserva-com-uso-da-filtragem[m
  feature/PDM-28-mudancas-de-icones-na-barra-de-navegacao[m
  feature/PDM-29-melhorar-visibilidade-do-conteudo-principal-de-for[m
  fix/PDM-14[m
* [32mmain[m
  r[m
  [31mremotes/origin/dev[m
  [31mremotes/origin/feature/PDM-17-melhorar-apresentacao-em-telas-grandes[m
  [31mremotes/origin/feature/PDM-18-teste[m
  [31mremotes/origin/feature/PDM-19-testes[m
  [31mremotes/origin/feature/PDM-20-outros-testes[m
  [31mremotes/origin/feature/PDM-21-testelalal[m
  [31mremotes/origin/feature/PDM-22-criando-validacao-do-usuario-por-meio-do-jwt[m
  [31mremotes/origin/feature/PDM-23-teste12312321321[m
  [31mremotes/origin/feature/PDM-25-teste-da-tarefa[m
  [31mremotes/origin/feature/PDM-26-novo-teste[m
  [31mremotes/origin/feature/PDM-27-ajuste-na-reserva-com-uso-da-filtragem[m
  [31mremotes/origin/feature/PDM-28-mudancas-de-icones-na-barra-de-navegacao[m
  [31mremotes/origin/feature/PDM-29-melhorar-visibilidade-do-conteudo-principal-de-for[m
  [31mremotes/origin/feature/PDM-39-definir-paleta-cinza-100-900[m
  [31mremotes/origin/feature/PDM-40-criar-tokens-globais-de-cores[m
  [31mremotes/origin/feature/PDM-41-atualizar-tema-no-tailwind-css[m
  [31mremotes/origin/feature/PDM-43-ajustar-botoes-textos-backgrounds[m
  [31mremotes/origin/feature/PDM-44-atualizar-mini-design-system[m
  [31mremotes/origin/feature/PDM-45-atualizar-paleta-da-home[m
  [31mremotes/origin/fix/PDM-14[m
  [31mremotes/origin/main[m
